/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes a clock with no external reference
 */
export interface ClockWithNoExternalReference {
  /**
   * Name of this refclock (unique for this set of clocks)
   */
  name: string;
  /**
   * Type of external reference used by this clock
   */
  ref_type: "internal";
  [k: string]: unknown;
}
