/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes a clock referenced to PTP
 */
export interface PTPClock {
  /**
   * Name of this refclock (unique for this set of clocks)
   */
  name: string;
  /**
   * Type of external reference used by this clock
   */
  ref_type: "ptp";
  /**
   * External refclock is synchronised to International Atomic Time (TAI)
   */
  traceable: boolean;
  /**
   * Version of PTP reference used by this clock
   */
  version: "IEEE1588-2008";
  /**
   * ID of the PTP reference used by this clock
   */
  gmid: string;
  /**
   * Lock state of this clock to the external reference. If true, this device is slaved, otherwise it has no defined relationship to the external reference
   */
  locked: boolean;
  [k: string]: unknown;
}
