/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes the standard error response which is returned with HTTP codes 400 and above
 */
export interface ErrorResponse {
  /**
   * HTTP error code
   */
  code: number;
  /**
   * Human readable message which is suitable for user interface display, and helpful to the user
   */
  error: string;
  /**
   * Debug information which may assist a programmer working with the API
   */
  debug: null | string;
  [k: string]: unknown;
}
