import { FlowCore } from "./FlowCore";
/**
 * Describes a JSON based Flow
 */
export type FlowJsonData = FlowCore & {
    
    /**
     * Format of the data coming from the Flow as a URN
     */
    format : string,
    
    /**
     * Subclassification of the format using IANA assigned media types
     */
    media_type : string,
    
    /**
     * Event type generated by this Flow, if applicable
     */
    event_type? : string
};