/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes the possible requests to a Node's Receiver target resource
 */
export type ReceiverTargetResource = SenderResource | EmptyObjectSchema;
/**
 * Describes a sender
 */
export type SenderResource = BaseResource & {
  /**
   * Capabilities of this sender
   */
  caps?: {
    [k: string]: unknown;
  };
  /**
   * ID of the Flow currently passing via this Sender
   */
  flow_id: string | null;
  /**
   * Transport type used by the Sender in URN format
   */
  transport: {
    [k: string]: unknown;
  } & string;
  /**
   * Device ID which this Sender forms part of. This attribute is used to ensure referential integrity by registry implementations.
   */
  device_id: string;
  /**
   * HTTP(S) accessible URL to a file describing how to connect to the Sender.
   */
  manifest_href: string | null;
  /**
   * Binding of Sender egress ports to interfaces on the parent Node.
   */
  interface_bindings: string[];
  /**
   * Object containing the 'receiver_id' currently subscribed to (unicast only).
   */
  subscription: {
    /**
     * UUID of the Receiver that this Sender is currently subscribed to
     */
    receiver_id: string | null;
    /**
     * Sender is enabled and configured to send data
     */
    active: boolean;
    [k: string]: unknown;
  };
  [k: string]: unknown;
};

/**
 * Describes the foundations of all NMOS resources
 */
export interface BaseResource {
  /**
   * Globally unique identifier for the resource
   */
  id: string;
  /**
   * String formatted TAI timestamp (<seconds>:<nanoseconds>) indicating precisely when an attribute of the resource last changed
   */
  version: string;
  /**
   * Freeform string label for the resource
   */
  label: string;
  /**
   * Detailed description of the resource
   */
  description: string;
  /**
   * Key value set of freeform string tags to aid in filtering resources. Values should be represented as an array of strings. Can be empty.
   */
  tags: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "".
     */
    [k: string]: string[];
  };
  [k: string]: unknown;
}
/**
 * Describes an empty object
 */
export interface EmptyObjectSchema {}
