/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes the Node API base resource
 */
export type NodeAPIBaseResource = [
  "self/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/",
  "self/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/",
  "self/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/",
  "self/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/",
  "self/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/",
  "self/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/"
];
