/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes the Query API base resource
 */
export type QueryAPIBaseResource = [
  "nodes/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/" | "subscriptions/",
  "nodes/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/" | "subscriptions/",
  "nodes/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/" | "subscriptions/",
  "nodes/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/" | "subscriptions/",
  "nodes/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/" | "subscriptions/",
  "nodes/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/" | "subscriptions/",
  "nodes/" | "sources/" | "flows/" | "devices/" | "senders/" | "receivers/" | "subscriptions/"
];
