/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Describes a generic Source
 */
export type GenericSourceResource = SourceResource & {
  /**
   * Format of the data coming from the Source as a URN
   */
  format: "urn:x-nmos:format:video" | "urn:x-nmos:format:mux";
  [k: string]: unknown;
};
/**
 * Describes a Source
 */
export type SourceResource = BaseResource & {
  /**
   * Maximum number of Grains per second for Flows derived from this Source. Corresponding Flow Grain rates may override this attribute. Grain rate matches the frame rate for video (see NMOS Content Model). Specified for periodic Sources only.
   */
  grain_rate?: {
    /**
     * Numerator
     */
    numerator: number;
    /**
     * Denominator
     */
    denominator?: number;
    [k: string]: unknown;
  };
  /**
   * Capabilities (not yet defined)
   */
  caps: {
    [k: string]: unknown;
  };
  /**
   * Globally unique identifier for the Device which initially created the Source. This attribute is used to ensure referential integrity by registry implementations.
   */
  device_id: string;
  /**
   * Array of UUIDs representing the Source IDs of Grains which came together at the input to this Source (may change over the lifetime of this Source)
   */
  parents: string[];
  /**
   * Reference to clock in the originating Node
   */
  clock_name: string | null;
  [k: string]: unknown;
};

/**
 * Describes the foundations of all NMOS resources
 */
export interface BaseResource {
  /**
   * Globally unique identifier for the resource
   */
  id: string;
  /**
   * String formatted TAI timestamp (<seconds>:<nanoseconds>) indicating precisely when an attribute of the resource last changed
   */
  version: string;
  /**
   * Freeform string label for the resource
   */
  label: string;
  /**
   * Detailed description of the resource
   */
  description: string;
  /**
   * Key value set of freeform string tags to aid in filtering resources. Values should be represented as an array of strings. Can be empty.
   */
  tags: {
    /**
     * This interface was referenced by `undefined`'s JSON-Schema definition
     * via the `patternProperty` "".
     */
    [k: string]: string[];
  };
  [k: string]: unknown;
}
